name: Upload Model to S3

on:
    push:
        branches:
            - main

jobs:
    upload_model_to_s3:
        name: Upload Model to S3
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Upload dravnieks model to S3
          run: aws s3 mv saved-models/dravnieks_model.pth s3://qsor-gcn-models/dravnieks_model.pth

        - name: Upload goodscents model to S3
          run: aws s3 mv saved-models/goodscents_model.pth s3://qsor-gcn-models/goodscents_model.pth

        - name: Upload leffingwells model to S3
          run: aws s3 mv saved-models/leffingwells_model.pth s3://qsor-gcn-models/leffingwells_model.pth