name: Deploy Lambda

on:
    push:
        branches:
            - main

env:
    SAM_TEMPLATE: infrastructure/lambdas/template.yaml
    ARTIFACTS_BUCKET: qsor-lambda-artifacts

jobs:
    upload_model_to_s3:
        name: Deploy Lambda
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install zipper
          uses: montudor/action-zip@v1
        
        - name: Zip lambda
          run: zip -r lambda.zip infrastructure/lambdas/manage-fargate/

        - name: Set up AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Update lambda code
          run: |
            aws lambda update-function-code \
              --function-name fargate-manager \
              --zip-file fileb://lambda.zip"
















